version: '3.8'

services:
  akcse-server-rds:
    image: postgis/postgis
    restart: always
    container_name: 'akcse-server-rds'
    ports:
      - 5433:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=akcse
