version: '3.8'

services:
  akcse-server-rds:
    image: postgres:latest
    restart: always
    container_name: 'akcse-server-db'
    ports:
      - 5435:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=akcse
